

services:
  db:
    image: postgres:15
    container_name: postgres-musics
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: musics
    volumes:
      - postgres-data:/var/lib/postgresql/data


volumes:
  postgres-data:
